networks:
  net:
    driver: 'bridge'
    
services:
## https://www.linuxserver.io/blog/zero-trust-hosting-and-reverse-proxy-via-cloudflare-swag-and-authelia ##
 #flaresolverr: # Cloudflare Tunnel bypass
    #container_name: flaresolverr
    #image: ghcr.io/flaresolverr/flaresolverr:latest
    #restart: unless-stopped
    #environment:
    #networks:
     #- net
    #ports: 
      #- 8191:8191 # Listening port for FlareSolverr
    
      
  swag: # Nginx webserver + reverse proxy with built-in Certbot and Fail2ban
    container_name: swag
    image: lscr.io/linuxserver/swag:latest # https://github.com/linuxserver/docker-swag
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
    volumes:
      - /home/docker/swag/config:/home/docker/config
    networks:
      - net
    ports:
      - 80:80 # Nginx HTTP port
      - 443:443 # Nginx HTTPS port
    
  authelia: # Authelia Multi-Factor Authentication with SWAG intergration
    container_name: authelia
    image: ghcr.io/authelia/authelia:latest
    restart: unless-stopped
    volumes:
      - /home/docker/authelia/config:/home/docker/config
    networks:
      - net
  
  #gluetun: # VPN client with Mullvad support
    #container_name: gluetun
    #image: qmcgaw/gluetun:latest
    #restart: always
    #cap_add:
      #- NET_ADMIN
    #devices:
      #- /dev/net/tun:/dev/net/tun
    #ports:
      #- 8080:8080/tcp # qBit WebUi
      #- 8694:8694/tcp # qBit Torrenting
      #- 9696:9696/tcp # Prowlarr
      
  jellyfin: # Media server for streaming movies and TV shows.
    container_name: jellyfin
    image: lscr.io/linuxserver/jellyfin:latest # https://github.com/linuxserver/docker-jellyfin
    restart: unless-stopped
    devices: # Hardware devices, in this case hardware transcoding
      - /dev/dri/renderD128:/dev/dri/renderD128
    volumes: # 
      - /home/docker/jellyfin/config:/home/docker/config
      - /home/docker/jellyfin/media:/home/docker/media
    networks:
      - net
    ports:
      - 8096:8096 # Jellyfin HTTP port
      - 8920:8920 # Jellyfin HTTPS port

  sonarr: # Show manager
    container_name: sonarr
    image: lscr.io/linuxserver/sonarr:latest # https://github.com/linuxserver/docker-sonarr
    restart: unless-stopped
    volumes:
      - /home/docker/sonarr/config:/home/docker/config
    ports:
      - 8989:8989 #
        
  radarr: # Movie manager
    container_name: radarr
    image: lscr.io/linuxserver/radarr:latest # https://github.com/linuxserver/docker-radarr
    restart: unless-stopped
    volumes:
      - /home/docker/radarr/config:/home/docker/config
    ports:
      - 7878:7878 #
        
  prowlarr: # Sonnar and Radarr manager
    container_name: prowlarr
    image: lscr.io/linuxserver/prowlarr:latest # https://github.com/linuxserver/docker-prowlarr
    restart: unless-stopped
    volumes:
      - /home/docker/prowlarr/config:/home/docker/config
    ports:
      - 9696:9696 #
    
  bazarr:
    container_name: bazarr
    image: lscr.io/linuxserver/bazarr # https://github.com/linuxserver/docker-bazarr
    restart: unless-stopped
    volumes:
      - /home/docker/bazarr/data:/home/docker/data
      - /home/docker/bazarr/config:/home/docker/config
    ports:
      - 6767:6767 #
        
  qbittorrent: # Bittorrent client
    container_name: qbittorrent
    image: lscr.io/linuxserver/qbittorrent:latest # https://github.com/linuxserver/docker-qbittorrent
    restart: unless-stopped
    
  tdarr: # Automated transcoding
    container_name: tdarr
    image: ghcr.io/haveagitgat/tdarr:latest
    restart: unless-stopped
    devices:
      - /dev/dri:/dev/dri # Transcoding
    volumes:
      - /home/docker/tdarr/server:/home/docker/server
      - /home/docker//tdarr/config:/home/docker/config
      - /home/docker/tdarr/logs:/home/docker/logs
      - /home/docker/tdarr/temp:/home/docker/temp
      - /home/docker/tdarr/media:/home/docker/media
    ports:
      - 8265:8265 # Tdarr webUI port
      - 8266:8266 # Tdarr server port
    networks:
      - net
    
  jellyseerr: # Jellyfin request manager
    container_name: jellyseerr
    image: fallenbagel/jellyseerr:latest
    restart: unless-stopped
    volumes:
      - /home/docker/jellyseerr/data:/home/docker/data
    ports:
      - 5055:5055 # 
    networks:
      - net
    
  #hommarr: # Admin Dashboard
    #container_name: hommarr
    #image: ghcr.io/ajnart/homarr:latest
    #restart: unless-stopped

  #unpackarr:
    #image: ghcr.io/unpackerr/unpackerr:latest # https://github.com/Unpackerr/unpackerr

      
    #image: ghcr.io/flmorg/cleanuperr:latest # https://github.com/flmorg/cleanuperr
    #image: ghcr.io/manimatter/decluttarr:latest # https://github.com/ManiMatter/decluttarr
